from django.urls import path, re_path
from . import views

urlpatterns = [
    path('authentication/login', views.login, name="login"),
    path('authentication/logout', views.logout, name='logout'),
    path('authentication/register-player',
         views.registration_player, name='registrationPlayer'),
    path('authentication/register-owner',
         views.registration_owner, name='registrationOwner'),
    path('filtered-sport-halls/', views.get_filtered_sport_halls,
         name='getFilteredSportHalls'),
    path('authentication/forgot-password',
         views.forgot_password, name='forgotPassword'),
    re_path(r'^authentication/confirm-email/$',
            views.confirm_email, name='confirm_email'),
    path('players', views.get_all_players, name='getAllUsers'),
    path('owners', views.get_all_owners, name='getAllOwners'),
    path('sport-halls', views.get_all_sport_halls, name='getAllSportHalls'),
    path('add-sport-hall', views.add_new_sport_hall, name='addNewSportHall'),
    path('get-sport-hall', views.get_sport_hall, name='getSportHall'),
    path('get-sport-hall-user', views.get_sport_hall_user, name='getSportHallUser'),
    path('get-sport-hall-reservations', views.get_sport_hall_reservations, name='getSportHallReservations'),
    path('get-friends', views.get_friends, name='getFriends'),
    path('remove-sport-hall', views.remove_sport_hall, name='removeSportHall'),
    path('change-sport-hall-status',
         views.change_sporthall_status, name='changeSportHallStatus'),
    path('createTeam/', views.create_team, name='createTeam'),
    path('getTeams/', views.get_perm_teams, name='getTeams'),
    path('deleteTeam/', views.delete_team, name='deleteTeam'),
    path('inviteTeamMember/', views.invite_team_member, name='inviteTeamMember'),
    path('deleteTeamMember/', views.delete_team_member, name='deleteTeamMember'),
    path('contact-us', views.contact_us, name='contactUs'),
    path('player/<int:id>', views.get_player_data, name="getPlayerData"),
    path('owner/<int:id>', views.get_owner_data, name="getOwnerData"),
    path('player/update/<int:id>', views.update_player_data, name="updatePlayerData"),
    path('player/change-password/<int:id>', views.update_player_password, name="updateUserPassword"),
    path('player/change-profile-photo/<int:id>', views.update_player_photo, name="updateUserPhoto"),
    path('owner/update/<int:id>', views.update_owner_data, name="updateOwner"),
    path('owner/change-password/<int:id>', views.update_owner_password, name="updateOwnerPassword"),
    path('reservation', views.reservation, name='reservation'),
    path('get-permanent-teams', views.get_permanent_teams, name='getPermanentTeams'),
    path('get-users', views.get_users, name='getUsers'),
    path('get-invited-users', views.get_invited_users, name='getInvitedUsers'),
    path('invite-temporary-team', views.invite_temporary_team, name='inviteTemporaryTeam'),
    path('remove-invite-temporary-team',
         views.remove_invite_temporary_team, name='removeInviteTemporaryTeam'),
    path('player/update-invitation-status/<int:id>', views.update_invitation_status, name="updateInvitationStatus"),
    path('player/invitations/<int:id>', views.get_player_invitations, name="getPlayerInvitations"),
    path('player/friends/<int:id>', views.get_player_friends, name="getPlayerFriends"),
    path('player/delete-friend/<int:id>', views.delete_player_friend, name="deletePlayerFriend"),
    path('player/sort-invitations/<int:id>', views.sort_player_invitations, name="sortPlayerInvitations"),
    path('player/sort-history/<int:id>', views.sort_player_history, name="sortPlayerHistory"),
    path('player/sort-friends/<int:id>', views.sort_player_friends, name="sortPlayerFriends"),
    path('player/games/<int:id>', views.get_player_games, name="getPlayerGames"),
]
