# Generated by Django 4.2 on 2023-05-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('location', models.TextField(null=True)),
                ('tel_number', models.CharField(max_length=20, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('picture', models.TextField(null=True)),
                ('access_token', models.TextField(null=True)),
                ('confirmation_token', models.TextField(null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50, null=True)),
                ('tel_number', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(null=True)),
                ('interests', models.TextField(null=True)),
                ('picture', models.TextField(null=True)),
                ('access_token', models.TextField(null=True)),
                ('confirmation_token', models.TextField(null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.team')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.user')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='team_lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sportsman.user'),
        ),
        migrations.CreateModel(
            name='SportHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField(null=True)),
                ('description', models.CharField(max_length=5000, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('price', models.FloatField()),
                ('sports', models.TextField(null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('pictures', models.TextField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.owner')),
            ],
        ),
        migrations.CreateModel(
            name='PermanentTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.team')),
            ],
        ),
        migrations.CreateModel(
            name='Owner_SportHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.owner')),
                ('sporthall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.sporthall')),
            ],
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(null=True)),
                ('status', models.IntegerField()),
                ('details', models.TextField(null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='sportsman.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='sportsman.user')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('time_appointed', models.DateTimeField(null=True)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.team')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends1', to='sportsman.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends2', to='sportsman.user')),
            ],
        ),
    ]
