# Generated by Django 4.2 on 2023-06-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50, null=True)),
                ('tel_number', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(null=True)),
                ('interests', models.CharField(max_length=500, null=True)),
                ('picture', models.CharField(max_length=500, null=True)),
                ('access_token', models.TextField(null=True)),
                ('confirmation_token', models.TextField(null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sportsman.user')),
                ('location', models.TextField(null=True)),
                ('capacity', models.IntegerField(null=True)),
            ],
            bases=('sportsman.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.usertype'),
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.team')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.user')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='team_lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sportsman.user'),
        ),
        migrations.CreateModel(
            name='SportHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField(null=True)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=20, null=True)),
                ('pictures', models.TextField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('sports', models.ManyToManyField(to='sportsman.sport')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('time_from', models.TimeField(null=True)),
                ('time_to', models.TimeField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('tel_number', models.CharField(max_length=20)),
                ('team_id', models.IntegerField(null=True)),
                ('sport_hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.sporthall')),
            ],
        ),
        migrations.CreateModel(
            name='PermanentTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, null=True)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.team')),
            ],
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(null=True)),
                ('status', models.IntegerField()),
                ('details', models.TextField(null=True)),
                ('invitation_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportsman.invitationtype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='sportsman.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='sportsman.user')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_appointed', models.DateTimeField(null=True)),
                ('sport_hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.sporthall')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.status')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.team')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends1', to='sportsman.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends2', to='sportsman.user')),
            ],
        ),
        migrations.CreateModel(
            name='Owner_SportHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.sporthall')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.owner')),
            ],
        ),
    ]
