# Generated by Django 4.2 on 2023-06-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('tel_number', models.CharField(max_length=20)),
                ('reservation_type', models.CharField(max_length=20)),
                ('reservation_by', models.IntegerField()),
            ],
        ),
    ]
