# Generated by Django 4.2.1 on 2023-05-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='time_sent',
            field=models.DateTimeField(),
        ),
    ]
