# Generated by Django 4.2 on 2023-04-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='UserTypes',
            new_name='UserType',
        ),
    ]
