# Generated by Django 4.2.1 on 2023-06-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='games',
            name='hall_name',
        ),
        migrations.RemoveField(
            model_name='invitations',
            name='type',
        ),
        migrations.AddField(
            model_name='games',
            name='sport_hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.sporthall'),
        ),
        migrations.AddField(
            model_name='invitations',
            name='invitation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportsman.invitationtype'),
        ),
    ]
