# Generated by Django 4.2.1 on 2023-06-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0002_invitationtype_remove_games_hall_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='sporthall',
            name='sports',
        ),
        migrations.AddField(
            model_name='sporthall',
            name='sports',
            field=models.ManyToManyField(to='sportsman.sport'),
        ),
    ]
