# Generated by Django 4.2.1 on 2023-06-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0002_alter_invitations_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='time_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
