# Generated by Django 4.2 on 2023-06-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0002_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='reservation_by',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='reservation_type',
        ),
        migrations.AddField(
            model_name='reservations',
            name='date_time_begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='date_time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='sport_hall_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportsman.sporthall'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportsman.user'),
        ),
    ]
