# Generated by Django 4.2 on 2023-06-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0003_remove_reservations_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='sport_hall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.sporthall'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.user'),
        ),
    ]
