# Generated by Django 4.2.1 on 2023-06-16 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0003_sport_remove_sporthall_sports_sporthall_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporthall',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportsman.owner'),
            preserve_default=False,
        ),
    ]
