# Generated by Django 4.2.1 on 2023-05-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0004_remove_owner_typeofuser_remove_user_typeofuser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permanent_teams',
            new_name='PermanentTeams',
        ),
        migrations.RenameModel(
            old_name='Sport_hall',
            new_name='SportHall',
        ),
        migrations.RenameModel(
            old_name='Team_members',
            new_name='TeamMembers',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('renter', 'user'), ('owner', 'User')], default='owner', max_length=10),
        ),
    ]
