# Generated by Django 4.2 on 2023-06-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0005_remove_reservations_date_time_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentteams',
            name='team_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
