# Generated by Django 4.2.1 on 2023-05-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0005_rename_permanent_teams_permanentteams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('owner', 'Owner')], default='owner', max_length=10),
        ),
    ]
