# Generated by Django 4.2 on 2023-05-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0007_user_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('owner', 'Owner')], default='player', max_length=10),
        ),
    ]
