# Generated by Django 4.2 on 2023-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0008_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='owner',
            name='access_token',
            field=models.TextField(null=True),
        ),
    ]
