# Generated by Django 4.2 on 2023-05-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0009_remove_user_role_owner_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporthall',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
