# Generated by Django 4.2.1 on 2023-05-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0009_remove_user_role_owner_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='confirmation_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_token',
            field=models.TextField(null=True),
        ),
    ]
