# Generated by Django 4.2 on 2023-05-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0010_sporthall_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sporthall',
            name='pictures',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
