# Generated by Django 4.2.1 on 2023-05-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0010_owner_confirmation_token_user_confirmation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
