# Generated by Django 4.2.1 on 2023-05-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0011_owner_last_login_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
