# Generated by Django 4.2 on 2023-05-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0011_alter_owner_picture_alter_sporthall_pictures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_SportHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.owner')),
                ('sporthall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsman.sporthall')),
            ],
        ),
    ]
