# Generated by Django 4.2.1 on 2023-05-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0012_owner_email_confirmed_user_email_confirmed'),
        ('sportsman', '0012_owner_sporthall'),
    ]

    operations = [
    ]
