# Generated by Django 4.2 on 2023-05-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0008_sporthall_sports_sporthall_type'),
        ('sportsman', '0012_owner_sporthall'),
    ]

    operations = [
    ]
