# Generated by Django 4.2 on 2023-06-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0012_owner_sporthall'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='type',
            field=models.CharField(default='Permanent Team', max_length=20),
        ),
        migrations.AddField(
            model_name='permanentteams',
            name='team_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
