# Generated by Django 4.2 on 2023-05-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0013_merge_20230522_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporthall',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
