# Generated by Django 4.2 on 2023-05-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0014_alter_sporthall_description'),
        ('sportsman', '0014_alter_sporthall_pictures'),
    ]

    operations = [
    ]
