# Generated by Django 4.2 on 2023-05-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0015_merge_20230523_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='picture',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.TextField(null=True),
        ),
    ]
