# Generated by Django 4.2 on 2023-05-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0016_alter_owner_picture_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
